=== GSA/datagov-harvester/archive/data/dcatus/schemas/catalog.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Project Open Data Catalog",
  "description": "Validates an entire collection of common core metadata JSON objects. Agencies produce said collections in the form of Data.json files.",
  "type": "object",
  "required": ["conformsTo", "dataset"],
  "properties": {
    "@context": {
      "title": "Metadata Context",
      "description": "URL or JSON object for the JSON-LD Context that defines the schema used",
      "type": "string",
      "format": "uri"
    },
    "@id": {
      "title": "Metadata Catalog ID",
      "description": "IRI for the JSON-LD Node Identifier of the Catalog. This should be the URL of the data.json file itself.",
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "title": "Metadata Context",
      "description": "IRI for the JSON-LD data type. This should be dcat:Catalog for the Catalog",
      "const": "dcat:Catalog"
    },
    "conformsTo": {
      "description": "Version of Schema",
      "title": "Version of Schema",
      "const": "https://project-open-data.cio.gov/v1.1/schema"
    },
    "describedBy": {
      "description": "URL for the JSON Schema file that defines the schema used",
      "title": "Data Dictionary",
      "type": "string",
      "format": "uri"
    },
    "dataset": {
      "type": "array",
      "items": {
        "$ref": "dataset.json",
        "minItems": 1,
        "uniqueItems": true
      }
    }
  },
  "$id": "https://project-open-data.cio.gov/v1.1/schema/catalog.json#",
  "dependentRequired": {
    "@type": ["@context"]
  }
}

=== GSA/datagov-harvester/archive/data/dcatus/jsons/arm.data.json
{
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@type": "dcat:Catalog",
  "dataset": [
    {
      "accessLevel": "public",
      "bureauCode": [
        "018:001"
      ],
      "license": "https://project-open-data.cio.gov/unknown-license",
      "identifier": "ncepgfsbrwpprof",
      "contactPoint": {
        "hasEmail": "mailto:adc@arm.gov",
        "fn": "ARM Data Center"
      },
      "description": "No description found",
      "programCode": [
        "018:001"
      ],
      "distribution": [
        {
          "accessURL": "http://www.archive.arm.gov/discovery/#v/results/s/s::ncepgfsbrwpprof",
          "format": "cdf"
        }
      ],
      "modified": "2019-06-27 12:41:27",
      "publisher": {
        "name": "Atmospheric Radiation Measurement Data Center",
        "subOrganizationOf": {
          "name": "DOE Biological and Environmental Research (BER)",
          "subOrganizationOf": {
            "name": "DOE Office of Science user facilities",
            "subOrganizationOf": {
              "name": "U.S. Government"
            }
          }
        }
      },
      "@type": "dcat:Dataset",
      "keyword": [
        "ARM",
        "ORNL",
        "ADC",
        "ARM Data Center",
        "Climate",
        "Atmospheric Data",
        "ncepgfs",
        "National Centers for Environment Prediction Global Forecast System",
        "derivmod"
      ],
      "title": "NCEP GFS: vertical profiles of met quantities at standard pressures, at Barrow"
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "018:001"
      ],
      "license": "https://project-open-data.cio.gov/unknown-license",
      "identifier": "10.5439/1027266",
      "contactPoint": {
        "hasEmail": "mailto:adc@arm.gov",
        "fn": "ARM Data Center"
      },
      "description": "No description found",
      "programCode": [
        "018:001"
      ],
      "distribution": [
        {
          "accessURL": "http://www.archive.arm.gov/discovery/#v/results/s/s::1swfanalskyrad1long",
          "format": "cdf"
        }
      ],
      "modified": "2019-06-27 12:41:27",
      "publisher": {
        "name": "Atmospheric Radiation Measurement Data Center",
        "subOrganizationOf": {
          "name": "DOE Biological and Environmental Research (BER)",
          "subOrganizationOf": {
            "name": "DOE Office of Science user facilities",
            "subOrganizationOf": {
              "name": "U.S. Government"
            }
          }
        }
      },
      "@type": "dcat:Dataset",
      "keyword": [
        "ARM",
        "ORNL",
        "ADC",
        "ARM Data Center",
        "Climate",
        "Atmospheric Data",
        "swfluxanal",
        "Shortwave Flux Analysis",
        "cloud",
        "swfluxanal",
        "Shortwave Flux Analysis",
        "radio"
      ],
      "title": "Short Wave Flux Analysis: 1-min resolution on SKYAD data, Long algorithm"
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "018:001"
      ],
      "license": "https://project-open-data.cio.gov/unknown-license",
      "identifier": "avhrr12",
      "contactPoint": {
        "hasEmail": "mailto:adc@arm.gov",
        "fn": "ARM Data Center"
      },
      "description": "No description found",
      "programCode": [
        "018:001"
      ],
      "distribution": [
        {
          "accessURL": "http://www.archive.arm.gov/discovery/#v/results/s/s::avhrr12",
          "format": "hdfjpg"
        }
      ],
      "modified": "2019-06-27 12:41:27",
      "publisher": {
        "name": "Atmospheric Radiation Measurement Data Center",
        "subOrganizationOf": {
          "name": "DOE Biological and Environmental Research (BER)",
          "subOrganizationOf": {
            "name": "DOE Office of Science user facilities",
            "subOrganizationOf": {
              "name": "U.S. Government"
            }
          }
        }
      },
      "@type": "dcat:Dataset",
      "keyword": [
        "ARM",
        "ORNL",
        "ADC",
        "ARM Data Center",
        "Climate",
        "Atmospheric Data",
        "avhrr",
        "Advanced Very High Resolution Radiometer",
        "satellite"
      ],
      "title": "AVHRR: albedo and brightness temp., NOAA-12 Satellite"
    }
  ]
}

=== GSA/datagov-harvester/example_data/dcatus/dcatus.json
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "http://www.cftc.gov/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [
    {
      "contactPoint": {
        "fn": "Harold W. Hild",
        "hasEmail": "mailto:hhild@CFTC.GOV"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/ExplanatoryNotes/index.htm",
      "description": "COT reports provide a breakdown of each Tuesday's open interest for futures and options on futures market in which 20 or more traders hold positions equal to or above the reporting levels established by CFTC",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm"
        }
      ],
      "modified": "R/P1W",
      "programCode": [
        "000:000"
      ],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Commitment of Traders",
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "identifier": "cftc-dc1",
      "keyword": [
        "commitment of traders",
        "cot",
        "open interest"
      ],
      "spatial": "United States"
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "contactPoint": {
        "fn": "Harold W. Hild",
        "hasEmail": "mailto:hhild@CFTC.GOV"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/BankParticipationReports/ExplanatoryNotes/index.htm",
      "description": "The Bank Participation Report (BPR), developed by the Division of Market Oversight to provide the U.S. banking authorities and the Bank for International Settlements (BIS, located in Basel, Switzerland) aggregate large-trader positions of banks participating in various financial and non-financial commodity futures.",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/BankParticipationReports/index.htm"
        }
      ],
      "identifier": "cftc-dc2",
      "keyword": [
        "bank participation report",
        "bpr",
        "banking"
      ],
      "modified": "R/P1M",
      "programCode": [
        "000:000"
      ],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Bank Participation Reports"
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "contactPoint": {
        "fn": "Harold W. Hild",
        "hasEmail": "mailto:hhild@CFTC.gov"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/CottonOnCall/index.htm",
      "description": "Cotton On-Call Report shows the quantity of call cotton bought or sold on which the price has not been fixed, together with the respective futures on which the purchase or sale is based on.",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/CottonOnCall/index.htm"
        }
      ],
      "identifier": "cftc-dc3",
      "keyword": [
        "cotton on call",
        "cotton on-call"
      ],
      "modified": "R/P1W",
      "programCode": [
        "000:000"
      ],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Cotton On Call"
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "contactPoint": {
        "fn": "Carrie L Coffin",
        "hasEmail": "mailto:ccoffin@CFTC.gov"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/financialfcmdata/DescriptionofReportDataFields/indesx.htm",
      "description": "Futures commission merchants (FCMs) and retail foreign exchange dealers (RFEDs) must file monthly financial reports with the CFTC's Market Participants Division (MPD) within 17 business days after the end of the month. Selected financial information from these reports is published.",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/financialfcmdata/index.htm"
        }
      ],
      "identifier": "cftc-dc4",
      "keyword": [
        "fcm",
        "retail foreign exchange",
        "dealer",
        "market participants",
        "mpd",
        "futures commission merchant"
      ],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Financial Data for FCMS",
      "modified": "R/P1M",
      "programCode": [
        "000:000"
      ]
    },
    {
      "identifier": "cftc-dc5",
      "keyword": [
        "net positions",
        "larger trader net position",
        "trading account net positions"
      ],
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "contactPoint": {
        "fn": "Byung-IL Seo",
        "hasEmail": "mailto:BSeo@CFTC.gov"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/LgTraderExplanatory.html",
      "description": "The Large Trader Net Position Changes and the Trading Account Net Position Changes data provides the public with a view of the amount of trading that results in net changes to positions at the trader level and at the account level.  The data reflects trading that changes or creates an end-of-day position, as contrasted with trading that does not change a traderâ€™s end-of-day net position, such as spread or day trading.",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/NetPositionChangesData/index.htm"
        }
      ],
      "modified": "2011-06-30",
      "programCode": [
        "000:000"
      ],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Net Positions Changes Data"
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "contactPoint": {
        "fn": "Richard Haynes",
        "hasEmail": "mailto:RHaynes@CFTC.gov"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/SwapsReports/DataDictionary/index.htm",
      "description": "The CFTC Swaps Report aggregates a comprehensive body of swap market data that was not previously reported to regulators or regulated entities, and makes that information freely available in a form that is readily usable by both market participants and the general public. The swaps market data included in publications produced by entities such as the BIS, ISDA, and the Office of the Comptroller of the Currency vary in scope and granularity, but none corresponds directly to the data stored in the CFTC's SDRs.",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/SwapsReports/index.htm"
        }
      ],
      "title": "Weekly Swaps Report",
      "identifier": "cftc-dc6",
      "keyword": [
        "swaps report",
        "swaps market"
      ],
      "modified": "R/P1W",
      "programCode": [
        "000:000"
      ],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      }
    },
    {
      "accessLevel": "public",
      "bureauCode": [
        "339:00"
      ],
      "contactPoint": {
        "fn": "Byung-IL Seo",
        "hasEmail": "mailto:BSeo@CFTC.gov"
      },
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Cleared Margin Reports",
      "describedBy": "https://www.cftc.gov/MarketReports/ClearedMarginReports/index.htm",
      "description": "Derivatives clearing organizations (DCOs) are required to file daily reports on initial margin with the CFTC's Division of Clearing and Risk (DCR). Aggregate initial margin summary information for Chicago Mercantile Exchange (CME), ICE Clear Credit (ICC), ICE Clear US (ICUS), ICE Clear Europe (ICEU), LCH Ltd., and LCH SA is published below. The information will generally be updated within ten business days of the end of each month.",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/ClearedMarginReports/index.htm"
        }
      ],
      "identifier": "cftc-dc7",
      "keyword": [
        "margin",
        "exchange"
      ],
      "modified": "R/P1M",
      "programCode": [
        "000:000"
      ]
    }
  ]
}

=== GSA/datagov-harvester/example_data/dcatus/dcatus_2.json
{
    "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
    "@id": "http://www.cftc.gov/data.json",
    "@type": "dcat:Catalog",
    "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
    "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
    "dataset": [
        {
            "contactPoint": {
                "fn": "Harold W. Hild",
                "hasEmail": "mailto:hhild@CFTC.GOV"
            },
            "describedBy": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/ExplanatoryNotes/index.htm",
            "description": "COT reports provide a breakdown of each Tuesday's open interest for futures and options on futures market in which 20 or more traders hold positions equal to or above the reporting levels established by CFTC",
            "distribution": [
                {
                    "accessURL": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm"
                }
            ],
            "modified": "R/P1W",
            "programCode": [
                "000:000"
            ],
            "publisher": {
                "name": "U.S. Commodity Futures Trading Commission",
                "subOrganizationOf": {
                    "name": "U.S. Government"
                }
            },
            "title": "Commitment of Traders",
            "accessLevel": "public",
            "bureauCode": [
                "339:00"
            ],
            "identifier": "cftc-dc1",
            "keyword": [
                "commitment of traders",
                "cot",
                "open interest"
            ]
        },
        {
            "accessLevel": "public",
            "bureauCode": [
                "339:00"
            ],
            "contactPoint": {
                "fn": "Harold W. Hild",
                "hasEmail": "mailto:hhild@CFTC.GOV"
            },
            "describedBy": "https://www.cftc.gov/MarketReports/BankParticipationReports/ExplanatoryNotes/index.htm",
            "description": "The Bank Participation Report (BPR), developed by the Division of Market Oversight to provide the U.S. banking authorities and the Bank for International Settlements (BIS, located in Basel, Switzerland) aggregate large-trader positions of banks participating in various financial and non-financial commodity futures.",
            "distribution": [
                {
                    "accessURL": "https://www.cftc.gov/MarketReports/BankParticipationReports/index.htm"
                }
            ],
            "identifier": "cftc-dc2",
            "keyword": [
                "bank participation report",
                "bpr",
                "banking"
            ],
            "modified": "R/P1M",
            "programCode": [
                "000:000"
            ],
            "publisher": {
                "name": "U.S. Commodity Futures Trading Commission",
                "subOrganizationOf": {
                    "name": "U.S. Government"
                }
            },
            "title": "Bank Participation Reports"
        },
        {
            "accessLevel": "public",
            "bureauCode": [
                "339:00"
            ],
            "contactPoint": {
                "fn": "Harold W. Hild",
                "hasEmail": "mailto:hhild@CFTC.gov"
            },
            "describedBy": "https://www.cftc.gov/MarketReports/CottonOnCall/index.htm",
            "description": "Cotton On-Call Report shows the quantity of call cotton bought or sold on which the price has not been fixed, together with the respective futures on which the purchase or sale is based on.",
            "distribution": [
                {
                    "accessURL": "https://www.cftc.gov/MarketReports/CottonOnCall/index.htm"
                }
            ],
            "identifier": "cftc-dc3",
            "keyword": [
                "cotton on call",
                "cotton on-call"
            ],
            "modified": "R/P1W",
            "programCode": [
                "000:000"
            ],
            "publisher": {
                "name": "U.S. Commodity Futures Trading Commission",
                "subOrganizationOf": {
                    "name": "U.S. Government"
                }
            },
            "title": "Cotton On Call"
        }
    ]
}

=== GSA/datagov-harvester/example_data/dcatus/dcatus_same_title_step_2.json
{
    "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
    "@id": "http://www.cftc.gov/data.json",
    "@type": "dcat:Catalog",
    "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
    "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
    "dataset": [
        {
            "contactPoint": {
                "fn": "Harold W. Hild",
                "hasEmail": "mailto:hhild@CFTC.GOV"
            },
            "describedBy": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/ExplanatoryNotes/index.htm",
            "description": "COT reports provide a breakdown of each Tuesday's open interest for futures and options on futures market in which 20 or more traders hold positions equal to or above the reporting levels established by CFTC",
            "distribution": [
                {
                    "accessURL": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm"
                }
            ],
            "modified": "R/P1W",
            "programCode": ["000:000"],
            "publisher": {
                "name": "U.S. Commodity Futures Trading Commission",
                "subOrganizationOf": {
                    "name": "U.S. Government"
                }
            },
            "title": "Commitment of Traders",
            "accessLevel": "public",
            "bureauCode": ["339:00"],
            "identifier": "cftc-dc1",
            "keyword": ["commitment of traders", "cot", "open interest"]
        },
        {
            "accessLevel": "public",
            "bureauCode": ["339:00"],
            "contactPoint": {
                "fn": "Harold W. Hild",
                "hasEmail": "mailto:hhild@CFTC.GOV"
            },
            "describedBy": "https://www.cftc.gov/MarketReports/BankParticipationReports/ExplanatoryNotes/index.htm",
            "description": "The Bank Participation Report (BPR), developed by the Division of Market Oversight to provide the U.S. banking authorities and the Bank for International Settlements (BIS, located in Basel, Switzerland) aggregate large-trader positions of banks participating in various financial and non-financial commodity futures.",
            "distribution": [
                {
                    "accessURL": "https://www.cftc.gov/MarketReports/BankParticipationReports/index.htm"
                }
            ],
            "identifier": "cftc-dc2",
            "keyword": ["changed", "key", "words", "to", "trigger", "update"],
            "modified": "R/P1M",
            "programCode": ["000:000"],
            "publisher": {
                "name": "U.S. Commodity Futures Trading Commission",
                "subOrganizationOf": {
                    "name": "U.S. Government"
                }
            },
            "title": "Commitment of Traders"
        }
    ]
}
