=== GSA/datagov-harvester/archive/data/dcatus/schemas/catalog.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Project Open Data Catalog",
  "description": "Validates an entire collection of common core metadata JSON objects. Agencies produce said collections in the form of Data.json files.",
  "type": "object",
  "required": ["conformsTo", "dataset"],
  "properties": {
    "@context": {
      "title": "Metadata Context",
      "description": "URL or JSON object for the JSON-LD Context that defines the schema used",
      "type": "string",
      "format": "uri"
    },
    "@id": {
      "title": "Metadata Catalog ID",
      "description": "IRI for the JSON-LD Node Identifier of the Catalog. This should be the URL of the data.json file itself.",
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "title": "Metadata Context",
      "description": "IRI for the JSON-LD data type. This should be dcat:Catalog for the Catalog",
      "const": "dcat:Catalog"
    },
    "conformsTo": {
      "description": "Version of Schema",
      "title": "Version of Schema",
      "const": "https://project-open-data.cio.gov/v1.1/schema"
    },
    "describedBy": {
      "description": "URL for the JSON Schema file that defines the schema used",
      "title": "Data Dictionary",
      "type": "string",
      "format": "uri"
    },
    "dataset": {
      "type": "array",
      "items": {
        "$ref": "dataset.json",
        "minItems": 1,
        "uniqueItems": true
      }
    }
  },
  "$id": "https://project-open-data.cio.gov/v1.1/schema/catalog.json#",
  "dependentRequired": {
    "@type": ["@context"]
  }
}

=== GSA/datagov-harvester/archive/data/dcatus/jsons/geospatial.data.json
{
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@type": "dcat:Catalog",
  "dataset": [
    {
      "@type": "dcat:Dataset",
      "title": "ConformsTo ISO Example: TIGER/Line Shapefile, 2013, nation, U.S., Current County and Equivalent National Shapefile", 
      "description": "The TIGER/Line shapefiles and related database files (.dbf) are an extract of selected geographic and cartographic information from the U.S. Census Bureau's Master Address File / Topologically Integrated Geographic Encoding and Referencing (MAF/TIGER) Database (MTDB). The MTDB represents a seamless national file with no overlaps or gaps between parts, however, each TIGER/Line shapefile is designed to stand alone as an independent data set, or they can be combined to cover the entire nation. The primary legal divisions of most states are termed counties. In Louisiana, these divisions are known as parishes. In Alaska, which has no counties, the equivalent entities are the organized boroughs, city and boroughs, municipalities, and for the unorganized area, census areas. The latter are delineated cooperatively for statistical purposes by the State of Alaska and the Census Bureau. In four states (Maryland, Missouri, Nevada, and Virginia), there are one or more incorporated places that are independent of any county organization and thus constitute primary divisions of their states. These incorporated places are known as independent cities and are treated as equivalent entities for purposes of data presentation. The District of Columbia and Guam have no primary divisions, and each area is considered an equivalent entity for purposes of data presentation. The Census Bureau treats the following entities as equivalents of counties for purposes of data presentation: Municipios in Puerto Rico, Districts and Islands in American Samoa, Municipalities in the Commonwealth of the Northern Mariana Islands, and Islands in the U.S. Virgin Islands. The entire area of the United States, Puerto Rico, and the Island Areas is covered by counties or equivalent entities. The boundaries for counties and equivalent entities are as of January 1of the shapefile release year, primarily as reported through the Census Bureau's Boundary and Annexation Survey (BAS).",
      "modified": "2013",
      "bureauCode": [
          "006:07"
      ],
      "programCode": [
          "006:012"
      ],
      "keyword": [
          "Nation",
          "Polygon",
          "United States",
          "U.S."
      ],
      "theme": ["geospatial"],
      "identifier": "tl_2013_us_county.shp.xml",
      "accessLevel": "public",
      "spatial": "[[-14.601813, -179.231086], [71.441059, 179.859681]]",
      "publisher": {
        "@type": "org:Organization",
        "name": "U.S. Department of Commerce, U.S. Census Bureau, Geography Division"
      }, 
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "pointOfContact - U.S. Department of Commerce, U.S. Census Bureau, Geography Division",
        "hasEmail": "mailto:ask@census.gov"
      }, 
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "Census Tiger County Lines for 2013",
          "downloadURL": "http://www2.census.gov/geo/tiger/TIGER2013/COUNTY/tl_2013_us_county.zip",
          "mediaType": "application/zip"
        },
        {
          "@type": "dcat:Distribution",
          "title": "[Anything valid here] Original Metadata",
          "downloadURL": "https://meta.geo.census.gov/data/existing/decennial/GEO/GPMB/TIGERline/TIGER2013/county/tl_2013_us_county.shp.iso.xml",
          "conformsTo": "http://www.isotc211.org/2005/gmd",
          "description": "[Not required] The metadata original format",
          "mediaType": "text/xml",
          "format": "XML"
        }
      ]
    },
    {
      "@type": "dcat:Dataset",
      "title": "ConformsTo CSDGM Example: Comprehensive Global Database of Earthquake-Induced Landslide Events", 
      "description": "Currently, there are many datasets describing landslides caused by individual earthquakes, and global inventories of earthquake-induced landslides (EQIL). However, until recently, there were no datasets that provide a comprehensive description of the impacts of earthquake-induced landslide events. In this data release, we present an up-to-date, comprehensive global database containing all literature-documented earthquake-induced landslide events for the 244-year period from 1772 through May 2020.The database represents an update of the catalog developed by Nowicki Jessee et al. (2020), which summarized events through 2016. The revised catalog contains 264 historical earthquakes, 153 of which include documented landslide fatality counts. The database includes (where available) information on earthquake size (moment magnitude (Mw), surface-wave magnitude (Ms), and body-wave magnitude (mb)), depth, earthquake fault type, date and time, location, the availability of a ShakeMap, which estimates the spatial distribution of ground shaking from the USGS ShakeMap system (Worden and Wald, 2016), the availability of a geospatial landslide inventory, information about landslide occurrence (number of landslides, area or volume of landsliding, area affected by landsliding, landslide magnitude), earthquake/landslide impact (total fatalities, landslide fatalities, and number of injuries due to the effects of the earthquake), and USGS Ground Failure Tool estimates (estimated area and population exposed to landsliding). The full dataset of all known landslide-triggering events is provided as “EQIL Database 2020.csv,” including information on the data source(s) for each data component. A subset of the dataset, showing only those events for which landslide fatality counts are available, is provided as “EQIL Database LSFatality 2020.csv.”", 
      "modified": "2020-07-13T17:31:25.399151",
      "bureauCode": [
          "010:12"
      ],
      "programCode": [
          "010:171"
      ],
      "keyword": [
          "USGS",
          "GHSC",
          "Earthquake Hazards",
          "Earthquake",
          "Landslide Hazards",
          "Landslide",
          "Earthquake-induced landslide",
          "Database"
      ],
      "theme": ["geospatial"],
      "identifier": "USGS:5ec70f9d82ce476925eddc9e",
      "accessLevel": "public",
      "spatial": "[[-90, -180], [90, 180]]",
      "publisher": {
        "@type": "org:Organization",
        "name": "U.S. Geological Survey"
      }, 
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "Anna Nowicki Jessee",
        "hasEmail": "mailto:manowick@iu.edu"
      }, 
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "Digital Data",
          "accessURL": "https://doi.org/10.5066/P9NWIRZZ"
        },
        {
          "@type": "dcat:Distribution",
          "title": "[Anything valid here] Original Metadata",
          "downloadURL": "https://data.usgs.gov/metadata/Geologic_Hazards_Science_Center/5ec70f9d82ce476925eddc9e.xml",
          "conformsTo": "http://www.fgdc.gov/schemas/metadata",
          "description": "[Not required] The metadata original format",
          "mediaType": "text/xml",
          "format": "XML"
        }
      ]
    }
  ]
}

=== GSA/datagov-harvester/archive/data/dcatus/jsons/null-spatial.data.json
{
  "@type": "dcat:Catalog",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "dataset": [
    {
      "identifier": "null-spatial",
      "accessLevel": "public",
      "contactPoint": {
        "hasEmail": "mailto:Alexis.Graves@ocio.usda.gov",
        "@type": "vcard:Contact",
        "fn": "Alexi Graves"
      },
      "programCode": [
        "005:059"
      ],
      "description": "Sample dataset. Spatial can be null",
      "title": "Sample Title NUll Spatial",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "http://www.dm.usda.gov/foia/docs/Copy%20of%20ECM%20Congressional%20Logs%20FY14.xls",
          "mediaType": "application/vnd.ms-excel",
          "title": "Congressional Logs for Fiscal Year 2014"
        }
      ],
      "license": "https://creativecommons.org/publicdomain/zero/1.0/",
      "bureauCode": [
        "005:12"
      ],
      "modified": "2014-10-03",
      "publisher": {
        "@type": "org:Organization",
        "name": "Department of Agriculture"
      },
      "spatial": null,
      "keyword": [
        "Congressional Logs"
      ]
    }
  ]
}

=== GSA/datagov-harvester/archive/data/dcatus/jsons/ny.data.json
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "https://data.ny.gov/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [ 
    {
      "accessLevel":"public",
      "landingPage":"https://data.ny.gov/d/22ew-dxez",
      "issued":"2016-07-21","@type":"dcat:Dataset",
      "modified":"2019-06-10",
      "keyword":[
        "rental assistance",
        "rent",
        "homeownership",
        "homeowner",
        "home",
        "buying",
        "homebuyer",
        "first-time",
        "lmi",
        "assistance",
        "mortgage",
        "loans",
        "sonyma"
      ],
      "contactPoint": {
        "@type":"vcard:Contact",
        "fn":"Open Data NY",
        "hasEmail":"mailto:opendata@its.ny.gov"
      },
      "publisher": {
        "@type":"org:Organization",
        "name":"State of New York"
        },
      "identifier":"https://data.ny.gov/api/views/22ew-dxez",
      "description":"Financial and Geographic Information on SONYMA Loans purchased since 2004.",
      "title":"State of New York Mortgage Agency (SONYMA) Loans Purchased: Beginning 2004",
      "distribution":[
        {
          "@type":"dcat:Distribution",
          "downloadURL":"https://data.ny.gov/api/views/22ew-dxez/rows.csv?accessType=DOWNLOAD",
          "mediaType":"text/csv"
        },
        {
          "mediaType":"application/rdf+xml",
          "downloadURL":"https://data.ny.gov/api/views/22ew-dxez/rows.rdf?accessType=DOWNLOAD",
          "describedBy":"https://data.ny.gov/api/views/22ew-dxez/columns.rdf",
          "describedByType":"application/rdf+xml",
          "@type":"dcat:Distribution"
        },
        {
          "mediaType":"application/json",
          "downloadURL":"https://data.ny.gov/api/views/22ew-dxez/rows.json?accessType=DOWNLOAD",
          "describedBy":"https://data.ny.gov/api/views/22ew-dxez/columns.json", 
          "describedByType":"application/json",
          "@type":"dcat:Distribution"
        },
        {
          "mediaType":"application/xml",
          "downloadURL":"https://data.ny.gov/api/views/22ew-dxez/rows.xml?accessType=DOWNLOAD",
          "describedBy":"https://data.ny.gov/api/views/22ew-dxez/columns.svc",
          "describedByType":"application/xml",
          "@type":"dcat:Distribution"
          }
        ],
      "theme":["Economic Development"]
    }
  ]
}

=== GSA/datagov-harvester/example_data/dcatus/dcatus_spatial_no_translate.json
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "http://www.cftc.gov/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [
    {
      "contactPoint": {
        "fn": "Harold W. Hild",
        "hasEmail": "mailto:hhild@CFTC.GOV"
      },
      "describedBy": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/ExplanatoryNotes/index.htm",
      "description": "COT reports provide a breakdown of each Tuesday's open interest for futures and options on futures market in which 20 or more traders hold positions equal to or above the reporting levels established by CFTC",
      "distribution": [
        {
          "accessURL": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm"
        }
      ],
      "modified": "R/P1W",
      "programCode": ["000:000"],
      "publisher": {
        "name": "U.S. Commodity Futures Trading Commission",
        "subOrganizationOf": {
          "name": "U.S. Government"
        }
      },
      "title": "Commitment of Traders (cant translate spatial)",
      "accessLevel": "public",
      "bureauCode": ["339:00"],
      "identifier": "cftc-dc1 (cant translate spatial)",
      "isPartOf": "some-collection-id",
      "keyword": ["commitment of traders", "cot", "open interest"],
      "spatial": "-500.5471, 36.1198, -89.5345, 40.596"
    }
  ]
}

=== GSA/datagov-harvester/archive/data/dcatus/jsons/usda.gov.data.json
{
  "@type": "dcat:Catalog",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "dataset": [
    {
      "identifier": "USDA-DM-002",
      "accessLevel": "public",
      "contactPoint": {
        "hasEmail": "mailto:Alexis.Graves@ocio.usda.gov",
        "@type": "vcard:Contact",
        "fn": "Alexi Graves"
      },
      "programCode": [
        "005:059"
      ],
      "description": "This dataset is Congressional Correspondence from the Office of the Executive Secretariat for the Department of Agriculture.",
      "title": "Department of Agriculture Congressional Logs for Fiscal Year 2014",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "http://www.dm.usda.gov/foia/docs/Copy%20of%20ECM%20Congressional%20Logs%20FY14.xls",
          "mediaType": "application/vnd.ms-excel",
          "title": "Congressional Logs for Fiscal Year 2014"
        }
      ],
      "license": "https://creativecommons.org/publicdomain/zero/1.0/",
      "bureauCode": [
        "005:12"
      ],
      "modified": "2014-10-03",
      "publisher": {
        "@type": "org:Organization",
        "name": "Department of Agriculture"
      },
      "keyword": [
        "Congressional Logs"
      ]
    },
    {
      "contactPoint": {
        "hasEmail": "mailto:ebaiello@fs.fed.us",
        "@type": "vcard:Contact",
        "fn": "USFS AGOL Admin"
      },
      "description": "<p>The National Forest Climate Change Maps project was developed by the Rocky Mountain Research Station (RMRS) and the Office of Sustainability and Climate to meet the needs of national forest managers for information on projected climate changes at a scale relevant to decision making processes, including forest plans. The maps use state-of-the-art science and are available for every national forest in the contiguous United States with relevant data coverage. Currently, the map sets include variables related to precipitation, air temperature, snow (including snow residence time and April 1 snow water equivalent), and stream flow.</p>\r\n\r\n<p>Historical (1975-2005) and future (2071-2090) precipitation and temperature data for the contiguous United States are ensemble mean values across 20 global climate models from the CMIP5 experiment (https://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-11-00094.1), downscaled to a 4 km grid. For more information on the downscaling method and to access the data, please see Abatzoglou and Brown, 2012 (https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/joc.2312) and the Northwest Knowledge Network (https://climate.northwestknowledge.net/MACA/). We used the MACAv2- Metdata monthly dataset; monthly precipitation values (mm) were summed over the season of interest (annual, winter, or summer). Absolute and percent change were then calculated between the historical and future time periods.</p>\r\n\r\n<p>Raster data are also available for download from RMRS site (https://www.fs.fed.us/rm/boise/AWAE/projects/NFS-regional-climate-change-maps/categories/us-raster-layers.html), along with pdf maps and detailed metadata (https://www.fs.fed.us/rm/boise/AWAE/projects/NFS-regional-climate-change-maps/downloads/NationalForestClimateChangeMapsMetadata.pdf).</p>\r\n\r\n<p><img src=\"https://farm8.staticflickr.com/7824/47007970771_22492043f6.jpg\" /></p>",
      "title": "Percent change in annual precipitation (CONUS) (Image Service)",
      "distribution": [
        {
          "accessURL": "http://enterprisecontent-usfs.opendata.arcgis.com/datasets/429428633a5e486289f6111d9cbe7065",
          "@type": "dcat:Distribution",
          "format": "Web page",
          "mediaType": "text/html",
          "title": "ArcGIS Open Dataset"
        },
        {
          "accessURL": "https://apps.fs.usda.gov/fsgisx01/rest/services/RDW_Climate/AvgAnnualPrecipPctChange_CONUS/ImageServer",
          "@type": "dcat:Distribution",
          "format": "Esri REST",
          "mediaType": "application/json",
          "title": "Esri Rest API"
        }
      ],
      "bureauCode": [
        "005:96"
      ],
      "modified": "2019-03-22",
      "theme": [
        "geospatial"
      ],
      "keyword": [
        "USDA Forest Service",
        "USFS",
        "Office of Sustainability and Climate",
        "OSC",
        "Rocky Mountain Research Station",
        "RMRS",
        "Air Water and Aquatic Environments Program",
        "AWAE",
        "climate",
        "climate change",
        "National Forests",
        "Open Data",
        "precipitation",
        "water yield",
        "CONUS",
        "contiguous US"
      ],
      "spatial": "-134.91336517510808,21.082969302706488,-56.90070213154654,52.37089914390312",
      "issued": "2017-11-22",
      "identifier": "http://enterprisecontent-usfs.opendata.arcgis.com/datasets/429428633a5e486289f6111d9cbe7065",
      "accessLevel": "public",
      "programCode": [
        "005:059"
      ],
      "landingPage": "http://enterprisecontent-usfs.opendata.arcgis.com/datasets/429428633a5e486289f6111d9cbe7065",
      "license": "https://hub.arcgis.com/api/v2/datasets/429428633a5e486289f6111d9cbe7065/license",
      "publisher": {
        "name": "U.S. Forest Service"
      }
    },
    {
      "contactPoint": {
        "hasEmail": "mailto:ebaiello@fs.fed.us",
        "@type": "vcard:Contact",
        "fn": "USFS AGOL Admin"
      },
      "description": "<p>The National Forest Climate Change Maps project was developed by the Rocky Mountain Research Station (RMRS) and the Office of Sustainability and Climate to meet the needs of national forest managers for information on projected climate changes at a scale relevant to decision making processes, including forest plans. The maps use state-of-the-art science and are available for every national forest in the contiguous United States with relevant data coverage. Currently, the map sets include variables related to precipitation, air temperature, snow (including snow residence time and April 1 snow water equivalent), and stream flow.</p>\r\n\r\n<p>Snow residence time (in days) and April 1 snow water equivalent (in mm) were modeled using the spatial analog models of Luce et al., 2014 (https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2013WR014844); see also Lute and Luce, 2017 (https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017WR020752). These models are built on precipitation and snow data from Snowpack Telemetry (SNOTEL) stations across the western United States and temperature data from the TopoWx dataset (https://rmets.onlinelibrary.wiley.com/doi/10.1002/joc.4127). They were calculated for the historical (1975-2005) and future (2071-2090) time periods, along with absolute and percent change.</p>\r\n\r\n<p>Raster data are also available for download from RMRS site (https://www.fs.fed.us/rm/boise/AWAE/projects/NFS-regional-climate-change-maps/categories/us-raster-layers.html), along with pdf maps and detailed metadata (https://www.fs.fed.us/rm/boise/AWAE/projects/NFS-regional-climate-change-maps/downloads/NationalForestClimateChangeMapsMetadata.pdf).</p>\r\n\r\n<p><img src=\"https://farm8.staticflickr.com/7880/47007969021_885cb1a4a5.jpg\" /></p>",
      "title": "Percent change in snow residence time (CONUS) (Image Service)",
      "distribution": [
        {
          "accessURL": "http://enterprisecontent-usfs.opendata.arcgis.com/datasets/f1879e9f6798461f8fd54719ea2231f8",
          "@type": "dcat:Distribution",
          "format": "Web page",
          "mediaType": "text/html",
          "title": "ArcGIS Open Dataset"
        },
        {
          "accessURL": "https://apps.fs.usda.gov/fsgisx01/rest/services/RDW_Climate/SnowResidenceTime_PctChange/ImageServer",
          "@type": "dcat:Distribution",
          "format": "Esri REST",
          "mediaType": "application/json",
          "title": "Esri Rest API"
        },
        {
          "accessURL": "https://apps.fs.usda.gov/fsgisx01/services/RDW_Climate/SnowResidenceTime_PctChange/ImageServer",
          "@type": "dcat:Distribution",
          "format": "OGC WMS",
          "mediaType": "application/vnd.ogc.wms_xml",
          "title": "OGC WMS"
        }
      ],
      "bureauCode": [
        "005:96"
      ],
      "modified": "2019-03-22",
      "theme": [
        "geospatial"
      ],
      "keyword": [
        "USDA Forest Service",
        "USFS",
        "Office of Sustainability and Climate",
        "OSC",
        "Rocky Mountain Research Station",
        "RMRS",
        "Air Water and Aquatic Environments Program",
        "AWAE",
        "climate",
        "climate change",
        "National Forests",
        "Open Data",
        "snow",
        "snow residence time",
        "SRT",
        "CONUS",
        "contiguous US"
      ],
      "spatial": "-134.91336517510808,21.082969302706488,-56.90070213154654,52.37089914390312",
      "issued": "2017-11-22",
      "identifier": "http://enterprisecontent-usfs.opendata.arcgis.com/datasets/f1879e9f6798461f8fd54719ea2231f8",
      "accessLevel": "public",
      "programCode": [
        "005:059"
      ],
      "landingPage": "http://enterprisecontent-usfs.opendata.arcgis.com/datasets/f1879e9f6798461f8fd54719ea2231f8",
      "license": "https://hub.arcgis.com/api/v2/datasets/f1879e9f6798461f8fd54719ea2231f8/license",
      "publisher": {
        "name": "U.S. Forest Service"
      }
    }
  ]
}

=== GSA/datagov-harvester/archive/data/dcatus/jsons/reserved-title.data.json
{
  "@type": "dcat:Catalog",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "dataset": [
    {
      "identifier": "bad-01",
      "accessLevel": "public",
      "contactPoint": {
        "hasEmail": "mailto:Alexis.Graves@ocio.usda.gov",
        "@type": "vcard:Contact",
        "fn": "Alexi Graves"
      },
      "programCode": [
        "005:059"
      ],
      "description": "Sample bad dataset. Should raise an Import error for using reserved words as title",
      "title": "Search",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "http://www.dm.usda.gov/foia/docs/Copy%20of%20ECM%20Congressional%20Logs%20FY14.xls",
          "mediaType": "application/vnd.ms-excel",
          "title": "Congressional Logs for Fiscal Year 2014"
        }
      ],
      "license": "https://creativecommons.org/publicdomain/zero/1.0/",
      "bureauCode": [
        "005:12"
      ],
      "modified": "2014-10-03",
      "publisher": {
        "@type": "org:Organization",
        "name": "Department of Agriculture"
      },
      "keyword": [
        "Congressional Logs"
      ]
    }
  ]
}
